pull_request_rules:
  - name: Automatic Sharp update merge
    conditions:
      - "check-success=build"
      - base=master
      - "label=sharp update"
    actions:
      merge:
        method: merge
