name: Build Layer ZIP

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Variables
      id: vars
      # from https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions
      run: |
        content=`cat ./package-lock.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=packageLockJson::$content"
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: hansottowirtz/amazon-linux-sharp-layer
        tag-sha: true
        tag-custom: dev,${{ fromJSON(steps.vars.outputs.packageLockJson).dependencies.sharp.version }}
    - name: Login to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
    - name: Copy artifacts
      run: docker run -v "${{ github.workspace }}/dist":/dist hansottowirtz/amazon-linux-sharp-layer:dev
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sharp-lambda-layer.zip
        path: dist/sharp-layer.zip
        if-no-files-found: error
    - name: Check size
      id: check_size
      run: |
        echo "::set-output name=size::$(du -h dist/sharp-layer.zip | grep -Po "\w+" | head -1)"
    - name: Create release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ fromJSON(steps.vars.outputs.packageLockJson).dependencies.sharp.version }}
        release_name: Version ${{ fromJSON(steps.vars.outputs.packageLockJson).dependencies.sharp.version }}
        body: |
          | Filename | Size |
          | --- | --- |
          | `sharp-lambda-layer.zip` | ${{ steps.check_size.outputs.size }} |
    - name: Upload release asset
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/sharp-layer.zip
        asset_name: sharp-lambda-layer.zip
        asset_content_type: application/zip